### ISSUE TITLE
Enum expected behavior when uninitialized

### ISSUE THREAD

**Issue by gkovelman** [Gilnaa/Hydras#14]
When defining an enum type variable in C, its value is 0 or undefined, based on the scope. It does not init with the first enum element. This means that it may be in undefined state, so it's up to the developer to handle the situation.

Hydras, on the other hand, initializes the variable with the first enum element. 

Is this the intended behavior? Shouldn't Hydras mimic C as much as possible?

**Comment by Gilnaa** [comment]
No, Hydras goal is not to mimic C, it is to parse and analyze memory structures with minimal effort.

That's also the reason why the library does not presume to handle alignment (unlike ctypes).

There's a case to be made that the library should default to the variant that has the value of 0, if it exists, but it doesn't make sense to default to 0 as is.
