### ISSUE TITLE
Scalars should inherit typing.SupportsInt

### ISSUE THREAD

**Issue by omertuc** [Gilnaa/Hydras#6]
The builtin int() function expects str, bytes or SupportsInt as shown:
![image](https://user-images.githubusercontent.com/10882062/68204433-a64f3500-ffd0-11e9-937a-aff575c8fbfb.png)
Scalars should inherit it so it's possible to call int() on them without a warning

**Comment by Gilnaa** [comment]
Sadly won't fix
